-- ============================================================
-- Squid Initial Schema — v1.0
-- Generated from final database state for first release.
-- All tables, sequences, indexes, constraints, and seed data.
-- ============================================================

CREATE TABLE action_channels (
    action_id integer NOT NULL,
    channel_id integer NOT NULL
);

CREATE TABLE action_environments (
    action_id integer NOT NULL,
    environment_id integer NOT NULL
);

CREATE TABLE action_excluded_environments (
    action_id integer NOT NULL,
    environment_id integer NOT NULL
);

CREATE TABLE action_machine_roles (
    action_id integer NOT NULL,
    machine_role character varying(100) NOT NULL
);

CREATE TABLE activity_log (
    id bigint NOT NULL,
    server_task_id integer NOT NULL,
    parent_id bigint,
    name character varying(500),
    node_type integer NOT NULL,
    category integer,
    status integer,
    log_text text,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    ended_at timestamp with time zone,
    sort_order integer DEFAULT 0 NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE SEQUENCE activity_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE activity_log_id_seq OWNED BY activity_log.id;

CREATE TABLE certificate (
    id integer NOT NULL,
    space_id integer NOT NULL,
    name character varying(255) NOT NULL,
    notes text,
    certificate_data text NOT NULL,
    password text,
    certificate_data_format integer DEFAULT 0 NOT NULL,
    thumbprint character varying(255) NOT NULL,
    subject_distinguished_name text,
    subject_common_name character varying(255),
    issuer_distinguished_name text,
    issuer_common_name character varying(255),
    self_signed boolean DEFAULT false NOT NULL,
    not_after timestamp with time zone NOT NULL,
    not_before timestamp with time zone NOT NULL,
    has_private_key boolean DEFAULT false NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    serial_number character varying(255),
    signature_algorithm_name character varying(255),
    subject_alternative_names text,
    environment_ids text,
    archived timestamp with time zone,
    replaced_by integer,
    last_modified_date timestamp with time zone NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE SEQUENCE certificate_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE certificate_id_seq OWNED BY certificate.id;

CREATE TABLE channel (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    project_id integer NOT NULL,
    lifecycle_id integer,
    data_version bytea NOT NULL,
    space_id integer NOT NULL,
    slug character varying(210) NOT NULL,
    description character varying(200),
    is_default boolean,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

ALTER TABLE channel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME channel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE channel_version_rules (
    id integer NOT NULL,
    channel_id integer NOT NULL,
    action_names text DEFAULT ''::text NOT NULL,
    version_range text DEFAULT ''::text NOT NULL,
    pre_release_tag text DEFAULT ''::text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL
);

CREATE SEQUENCE channel_version_rules_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE channel_version_rules_id_seq OWNED BY channel_version_rules.id;

CREATE TABLE deployment (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task_id integer,
    space_id integer NOT NULL,
    channel_id integer NOT NULL,
    project_id integer NOT NULL,
    release_id integer NOT NULL,
    environment_id integer NOT NULL,
    machine_id integer NOT NULL,
    "json" text NOT NULL,
    deployed_by integer NOT NULL,
    deployed_to_machine_ids text NOT NULL,
    process_snapshot_id integer,
    variable_set_snapshot_id integer,
    created_date timestamp with time zone NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE TABLE deployment_account (
    id integer NOT NULL,
    space_id integer NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    slug character varying(255) NOT NULL,
    environment_ids text,
    account_type integer NOT NULL,
    credentials text,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE SEQUENCE deployment_account_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE deployment_account_id_seq OWNED BY deployment_account.id;

CREATE TABLE deployment_action (
    id integer NOT NULL,
    step_id integer NOT NULL,
    action_order integer NOT NULL,
    name character varying(200) NOT NULL,
    action_type character varying(100) NOT NULL,
    worker_pool_id integer,
    is_disabled boolean DEFAULT false NOT NULL,
    is_required boolean DEFAULT true NOT NULL,
    can_be_used_for_project_versioning boolean DEFAULT false NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    feed_id integer,
    package_id character varying(500),
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

ALTER TABLE deployment_action ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME deployment_action_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE deployment_action_property (
    action_id integer NOT NULL,
    property_name character varying(200) NOT NULL,
    property_value text
);

CREATE TABLE deployment_completion (
    id integer NOT NULL,
    sequence_number bigint NOT NULL,
    deployment_id integer NOT NULL,
    state character varying(50) NOT NULL,
    completed_time timestamp with time zone NOT NULL,
    space_id integer NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

ALTER TABLE deployment_completion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME deployment_completion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE SEQUENCE deployment_completion_sequence_number_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE deployment_completion_sequence_number_seq OWNED BY deployment_completion.sequence_number;

CREATE TABLE deployment_environment (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    sort_order integer NOT NULL,
    "json" text NOT NULL,
    data_version bytea NOT NULL,
    space_id integer NOT NULL,
    slug character varying(210) NOT NULL,
    type character varying(50) NOT NULL,
    last_modified_date timestamp with time zone DEFAULT '0001-01-01 00:00:00+00'::timestamp with time zone NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE TABLE deployment_execution_checkpoint (
    id integer NOT NULL,
    server_task_id integer NOT NULL,
    deployment_id integer NOT NULL,
    last_completed_batch_index integer NOT NULL,
    failure_encountered boolean DEFAULT false NOT NULL,
    output_variables_json text,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE SEQUENCE deployment_execution_checkpoint_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE deployment_execution_checkpoint_id_seq OWNED BY deployment_execution_checkpoint.id;

CREATE SEQUENCE deployment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE deployment_id_seq OWNED BY deployment.id;

CREATE TABLE deployment_interruption (
    id integer NOT NULL,
    server_task_id integer NOT NULL,
    deployment_id integer NOT NULL,
    step_display_order integer DEFAULT 0 NOT NULL,
    step_name text,
    action_name text,
    machine_name text,
    error_message text,
    resolution text,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone,
    space_id integer DEFAULT 1 NOT NULL,
    interruption_type integer DEFAULT 1 NOT NULL,
    form_json text,
    submitted_values_json text,
    responsible_user_id text,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL,
    responsible_team_ids text
);

CREATE SEQUENCE "deployment_interruption_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE "deployment_interruption_Id_seq" OWNED BY deployment_interruption.id;

CREATE TABLE deployment_process (
    id integer NOT NULL,
    is_frozen boolean DEFAULT false NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    space_id integer NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    project_id integer DEFAULT 0 NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

ALTER TABLE deployment_process ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME deployment_process_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE deployment_process_snapshot (
    id integer NOT NULL,
    original_process_id integer NOT NULL,
    version integer NOT NULL,
    snapshot_data bytea NOT NULL,
    content_hash character varying(64) NOT NULL,
    compression_type character varying(20) DEFAULT 'GZIP'::character varying NOT NULL,
    uncompressed_size integer NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE TABLE deployment_step (
    id integer NOT NULL,
    process_id integer NOT NULL,
    step_order integer NOT NULL,
    name character varying(200) NOT NULL,
    step_type character varying(50) NOT NULL,
    condition text,
    start_trigger character varying(50),
    package_requirement character varying(50),
    is_disabled boolean DEFAULT false NOT NULL,
    is_required boolean DEFAULT true NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

ALTER TABLE deployment_step ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME deployment_step_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE deployment_step_property (
    step_id integer NOT NULL,
    property_name character varying(200) NOT NULL,
    property_value text
);

CREATE TABLE environment (
    id integer NOT NULL,
    space_id integer NOT NULL,
    slug character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    sort_order integer DEFAULT 0 NOT NULL,
    use_guided_failure boolean DEFAULT false NOT NULL,
    allow_dynamic_infrastructure boolean DEFAULT true NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

ALTER TABLE environment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME environment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE external_feed (
    id integer NOT NULL,
    feed_type character varying(255) NOT NULL,
    feed_uri text NOT NULL,
    username character varying(255),
    password text,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    package_acquisition_location_options text,
    space_id integer NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL,
    properties text
);

ALTER TABLE external_feed ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME external_feed_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE library_variable_set (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    variable_set_id integer,
    content_type character varying(50) NOT NULL,
    "json" text NOT NULL,
    space_id integer NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

ALTER TABLE library_variable_set ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME library_variable_set_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE lifecycle (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    data_version bytea NOT NULL,
    space_id integer NOT NULL,
    slug character varying(210) NOT NULL,
    release_retention_unit integer DEFAULT 0 NOT NULL,
    release_retention_quantity integer DEFAULT 0 NOT NULL,
    release_retention_keep_forever boolean DEFAULT true NOT NULL,
    tentacle_retention_unit integer DEFAULT 0 NOT NULL,
    tentacle_retention_quantity integer DEFAULT 0 NOT NULL,
    tentacle_retention_keep_forever boolean DEFAULT true NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

ALTER TABLE lifecycle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lifecycle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE machine (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    is_disabled boolean NOT NULL,
    roles text NOT NULL,
    environment_ids text NOT NULL,
    data_version bytea NOT NULL,
    slug character varying(210) NOT NULL,
    machine_policy_id integer,
    space_id integer,
    endpoint text,
    health_status character varying(50) DEFAULT 'Unknown'::character varying NOT NULL,
    health_last_checked timestamp with time zone,
    health_detail text,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

ALTER TABLE machine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME machine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE machine_policy (
    id integer NOT NULL,
    space_id integer NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    is_default boolean DEFAULT false NOT NULL,
    machine_health_check_policy text,
    machine_connectivity_policy text,
    machine_cleanup_policy text,
    machine_update_policy text,
    machine_rpc_call_retry_policy text,
    polling_request_queue_timeout text,
    connection_retry_sleep_interval text,
    connection_retry_count_limit integer DEFAULT 0 NOT NULL,
    connection_retry_time_limit text,
    connection_connect_timeout text,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE SEQUENCE machine_policy_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE machine_policy_id_seq OWNED BY machine_policy.id;

CREATE TABLE phase (
    id integer NOT NULL,
    lifecycle_id integer NOT NULL,
    name character varying(200) NOT NULL,
    minimum_environments_before_promotion integer NOT NULL,
    is_optional_phase boolean NOT NULL,
    is_priority_phase boolean NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    release_retention_unit integer,
    release_retention_quantity integer,
    release_retention_keep_forever boolean,
    tentacle_retention_unit integer,
    tentacle_retention_quantity integer,
    tentacle_retention_keep_forever boolean,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE TABLE phase_environment (
    phase_id integer NOT NULL,
    environment_id integer NOT NULL,
    target_type integer DEFAULT 0 NOT NULL
);

ALTER TABLE phase ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME phase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE SEQUENCE process_snapshot_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE process_snapshot_id_seq OWNED BY deployment_process_snapshot.id;

CREATE TABLE project (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(210) NOT NULL,
    is_disabled boolean NOT NULL,
    variable_set_id integer NOT NULL,
    deployment_process_id integer NOT NULL,
    project_group_id integer NOT NULL,
    lifecycle_id integer NOT NULL,
    auto_create_release boolean NOT NULL,
    "json" text NOT NULL,
    included_library_variable_set_ids text NOT NULL,
    discrete_channel_release boolean NOT NULL,
    data_version bytea NOT NULL,
    space_id integer NOT NULL,
    last_modified_date timestamp with time zone DEFAULT '0001-01-01 00:00:00+00'::timestamp with time zone NOT NULL,
    allow_ignore_channel_rules boolean DEFAULT true NOT NULL,
    cloned_from_project_id integer,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE TABLE project_group (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    space_id integer DEFAULT 1 NOT NULL,
    slug character varying(210) NOT NULL,
    data_version bytea DEFAULT '\x'::bytea NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE SEQUENCE project_group_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE project_group_id_seq OWNED BY project_group.id;

ALTER TABLE project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE release (
    id integer NOT NULL,
    version character varying(349) NOT NULL,
    created_date timestamp with time zone NOT NULL,
    project_id integer NOT NULL,
    project_variable_set_snapshot_id integer NOT NULL,
    project_deployment_process_snapshot_id integer NOT NULL,
    "json" text DEFAULT ''::text NOT NULL,
    channel_id integer NOT NULL,
    data_version bytea DEFAULT '\x00000000000000000000000000000000'::bytea NOT NULL,
    space_id integer NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

ALTER TABLE release ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME release_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE release_selected_package (
    id integer NOT NULL,
    release_id integer NOT NULL,
    action_name character varying(200) NOT NULL,
    version character varying(200) NOT NULL,
    package_reference_name character varying(200) DEFAULT ''::character varying NOT NULL
);

ALTER TABLE release_selected_package ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME release_selected_package_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE scoped_user_role (
    id integer NOT NULL,
    team_id integer NOT NULL,
    user_role_id integer NOT NULL,
    space_id integer,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 0 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 0 NOT NULL
);

CREATE TABLE scoped_user_role_environment (
    scoped_user_role_id integer NOT NULL,
    environment_id integer NOT NULL
);

CREATE SEQUENCE scoped_user_role_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE scoped_user_role_id_seq OWNED BY scoped_user_role.id;

CREATE TABLE scoped_user_role_project (
    scoped_user_role_id integer NOT NULL,
    project_id integer NOT NULL
);

CREATE TABLE scoped_user_role_project_group (
    scoped_user_role_id integer NOT NULL,
    project_group_id integer NOT NULL
);

CREATE TABLE server_task (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    description text NOT NULL,
    queue_time timestamp with time zone NOT NULL,
    start_time timestamp with time zone,
    completed_time timestamp with time zone,
    error_message text,
    concurrency_tag character varying(100),
    state character varying(50) NOT NULL,
    has_warnings_or_errors boolean NOT NULL,
    server_node_id uuid,
    project_id integer,
    environment_id integer,
    duration_seconds integer NOT NULL,
    data_version bytea DEFAULT '\x00000000000000000000000000000000'::bytea NOT NULL,
    space_id integer,
    last_modified_date timestamp with time zone DEFAULT '0001-01-01 00:00:00+00'::timestamp with time zone NOT NULL,
    business_process_state character varying(10) DEFAULT 'InProgress'::character varying NOT NULL,
    server_task_type character varying(50) DEFAULT 'ServerTask'::character varying NOT NULL,
    parent_server_task_id integer,
    priority_time timestamp with time zone,
    state_order integer DEFAULT 9 NOT NULL,
    weight integer DEFAULT 0 NOT NULL,
    batch_id integer,
    "json" text,
    job_id character varying(100),
    has_pending_interruptions boolean DEFAULT false NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

ALTER TABLE server_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME server_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE server_task_log (
    id bigint NOT NULL,
    server_task_id integer NOT NULL,
    category integer NOT NULL,
    message_text text,
    source character varying(500),
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    sequence_number bigint DEFAULT 0 NOT NULL,
    activity_node_id bigint,
    detail text,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE SEQUENCE server_task_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE server_task_log_id_seq OWNED BY server_task_log.id;

CREATE TABLE space (
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    slug character varying(20) NOT NULL,
    is_default boolean NOT NULL,
    "json" text NOT NULL,
    task_queue_stopped boolean NOT NULL,
    data_version bytea NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    is_private boolean DEFAULT false NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    owner_team_id integer
);

ALTER TABLE space ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME space_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE target_tag (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    space_id integer DEFAULT 1 NOT NULL
);

CREATE SEQUENCE target_tag_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE target_tag_id_seq OWNED BY target_tag.id;

CREATE TABLE team (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description text,
    space_id integer DEFAULT 1 NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 0 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 0 NOT NULL,
    is_built_in boolean DEFAULT false NOT NULL
);

CREATE SEQUENCE team_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE team_id_seq OWNED BY team.id;

CREATE TABLE team_member (
    team_id integer NOT NULL,
    user_id integer NOT NULL
);

CREATE TABLE user_account (
    id integer NOT NULL,
    user_name character varying(200) NOT NULL,
    normalized_user_name character varying(200) NOT NULL,
    display_name character varying(200) NOT NULL,
    password_hash text NOT NULL,
    is_disabled boolean DEFAULT false NOT NULL,
    is_system boolean DEFAULT false NOT NULL,
    created_date timestamp with time zone NOT NULL,
    last_modified_date timestamp with time zone NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL,
    must_change_password boolean DEFAULT false NOT NULL
);

CREATE TABLE user_account_api_key (
    id integer NOT NULL,
    user_account_id integer NOT NULL,
    api_key character varying(128) NOT NULL,
    description character varying(256),
    is_disabled boolean DEFAULT false NOT NULL,
    created_date timestamp with time zone NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE SEQUENCE user_account_api_key_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE user_account_api_key_id_seq OWNED BY user_account_api_key.id;

CREATE SEQUENCE user_account_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE user_account_id_seq OWNED BY user_account.id;

CREATE TABLE user_role (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    description text,
    is_built_in boolean DEFAULT false NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 0 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 0 NOT NULL
);

CREATE SEQUENCE user_role_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE user_role_id_seq OWNED BY user_role.id;

CREATE TABLE user_role_permission (
    user_role_id integer NOT NULL,
    permission character varying(100) NOT NULL
);

CREATE TABLE variable (
    id integer NOT NULL,
    variable_set_id integer NOT NULL,
    name character varying(200) NOT NULL,
    value text,
    description text,
    type integer DEFAULT 1 NOT NULL,
    is_sensitive boolean DEFAULT false NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL,
    prompt_label text,
    prompt_description text,
    prompt_required boolean DEFAULT false NOT NULL
);

CREATE SEQUENCE variable_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE variable_id_seq OWNED BY variable.id;

CREATE TABLE variable_scope (
    id integer NOT NULL,
    variable_id integer NOT NULL,
    scope_type integer NOT NULL,
    scope_value character varying(100) NOT NULL
);

CREATE SEQUENCE variable_scope_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE variable_scope_id_seq OWNED BY variable_scope.id;

CREATE TABLE variable_set (
    id integer NOT NULL,
    owner_type integer NOT NULL,
    owner_id integer NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    related_document_ids text,
    space_id integer NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    name character varying(200) DEFAULT ''::character varying NOT NULL,
    description text,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE SEQUENCE variable_set_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE variable_set_id_seq OWNED BY variable_set.id;

CREATE TABLE variable_set_snapshot (
    id integer NOT NULL,
    snapshot_data bytea NOT NULL,
    content_hash character varying(64) NOT NULL,
    compression_type character varying(20) DEFAULT 'GZIP'::character varying NOT NULL,
    uncompressed_size integer NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by integer DEFAULT 8888 NOT NULL,
    last_modified_date timestamp with time zone DEFAULT now() NOT NULL,
    last_modified_by integer DEFAULT 8888 NOT NULL
);

CREATE SEQUENCE variable_set_snapshot_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE variable_set_snapshot_id_seq OWNED BY variable_set_snapshot.id;

ALTER TABLE ONLY activity_log ALTER COLUMN id SET DEFAULT nextval('activity_log_id_seq'::regclass);

ALTER TABLE ONLY certificate ALTER COLUMN id SET DEFAULT nextval('certificate_id_seq'::regclass);

ALTER TABLE ONLY channel_version_rules ALTER COLUMN id SET DEFAULT nextval('channel_version_rules_id_seq'::regclass);

ALTER TABLE ONLY deployment ALTER COLUMN id SET DEFAULT nextval('deployment_id_seq'::regclass);

ALTER TABLE ONLY deployment_account ALTER COLUMN id SET DEFAULT nextval('deployment_account_id_seq'::regclass);

ALTER TABLE ONLY deployment_completion ALTER COLUMN sequence_number SET DEFAULT nextval('deployment_completion_sequence_number_seq'::regclass);

ALTER TABLE ONLY deployment_execution_checkpoint ALTER COLUMN id SET DEFAULT nextval('deployment_execution_checkpoint_id_seq'::regclass);

ALTER TABLE ONLY deployment_interruption ALTER COLUMN id SET DEFAULT nextval('"deployment_interruption_Id_seq"'::regclass);

ALTER TABLE ONLY deployment_process_snapshot ALTER COLUMN id SET DEFAULT nextval('process_snapshot_id_seq'::regclass);

ALTER TABLE ONLY machine_policy ALTER COLUMN id SET DEFAULT nextval('machine_policy_id_seq'::regclass);

ALTER TABLE ONLY project_group ALTER COLUMN id SET DEFAULT nextval('project_group_id_seq'::regclass);

ALTER TABLE ONLY scoped_user_role ALTER COLUMN id SET DEFAULT nextval('scoped_user_role_id_seq'::regclass);

ALTER TABLE ONLY server_task_log ALTER COLUMN id SET DEFAULT nextval('server_task_log_id_seq'::regclass);

ALTER TABLE ONLY target_tag ALTER COLUMN id SET DEFAULT nextval('target_tag_id_seq'::regclass);

ALTER TABLE ONLY team ALTER COLUMN id SET DEFAULT nextval('team_id_seq'::regclass);

ALTER TABLE ONLY user_account ALTER COLUMN id SET DEFAULT nextval('user_account_id_seq'::regclass);

ALTER TABLE ONLY user_account_api_key ALTER COLUMN id SET DEFAULT nextval('user_account_api_key_id_seq'::regclass);

ALTER TABLE ONLY user_role ALTER COLUMN id SET DEFAULT nextval('user_role_id_seq'::regclass);

ALTER TABLE ONLY variable ALTER COLUMN id SET DEFAULT nextval('variable_id_seq'::regclass);

ALTER TABLE ONLY variable_scope ALTER COLUMN id SET DEFAULT nextval('variable_scope_id_seq'::regclass);

ALTER TABLE ONLY variable_set ALTER COLUMN id SET DEFAULT nextval('variable_set_id_seq'::regclass);

ALTER TABLE ONLY variable_set_snapshot ALTER COLUMN id SET DEFAULT nextval('variable_set_snapshot_id_seq'::regclass);

ALTER TABLE ONLY action_channels
    ADD CONSTRAINT action_channels_pkey PRIMARY KEY (action_id, channel_id);

ALTER TABLE ONLY action_environments
    ADD CONSTRAINT action_environments_pkey PRIMARY KEY (action_id, environment_id);

ALTER TABLE ONLY action_excluded_environments
    ADD CONSTRAINT action_excluded_environments_pkey PRIMARY KEY (action_id, environment_id);

ALTER TABLE ONLY action_machine_roles
    ADD CONSTRAINT action_machine_roles_pkey PRIMARY KEY (action_id, machine_role);

ALTER TABLE ONLY activity_log
    ADD CONSTRAINT activity_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY certificate
    ADD CONSTRAINT certificate_pkey PRIMARY KEY (id);

ALTER TABLE ONLY channel
    ADD CONSTRAINT channel_pkey PRIMARY KEY (id);

ALTER TABLE ONLY channel_version_rules
    ADD CONSTRAINT channel_version_rules_pkey PRIMARY KEY (id);

ALTER TABLE ONLY deployment_account
    ADD CONSTRAINT deployment_account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY deployment_action
    ADD CONSTRAINT deployment_action_pkey PRIMARY KEY (id);

ALTER TABLE ONLY deployment_action_property
    ADD CONSTRAINT deployment_action_property_pkey PRIMARY KEY (action_id, property_name);

ALTER TABLE ONLY deployment_completion
    ADD CONSTRAINT deployment_completion_pkey PRIMARY KEY (id);

ALTER TABLE ONLY deployment_environment
    ADD CONSTRAINT deployment_environment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY deployment_execution_checkpoint
    ADD CONSTRAINT deployment_execution_checkpoint_pkey PRIMARY KEY (id);

ALTER TABLE ONLY deployment_interruption
    ADD CONSTRAINT deployment_interruption_pkey PRIMARY KEY (id);

ALTER TABLE ONLY deployment
    ADD CONSTRAINT deployment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY deployment_process
    ADD CONSTRAINT deployment_process_pkey PRIMARY KEY (id);

ALTER TABLE ONLY deployment_step
    ADD CONSTRAINT deployment_step_pkey PRIMARY KEY (id);

ALTER TABLE ONLY deployment_step_property
    ADD CONSTRAINT deployment_step_property_pkey PRIMARY KEY (step_id, property_name);

ALTER TABLE ONLY environment
    ADD CONSTRAINT environment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY external_feed
    ADD CONSTRAINT external_feed_pkey PRIMARY KEY (id);

ALTER TABLE ONLY library_variable_set
    ADD CONSTRAINT library_variable_set_pkey PRIMARY KEY (id);

ALTER TABLE ONLY lifecycle
    ADD CONSTRAINT lifecycle_pkey PRIMARY KEY (id);

ALTER TABLE ONLY machine
    ADD CONSTRAINT machine_pkey PRIMARY KEY (id);

ALTER TABLE ONLY machine_policy
    ADD CONSTRAINT machine_policy_pkey PRIMARY KEY (id);

ALTER TABLE ONLY phase_environment
    ADD CONSTRAINT phase_environment_pkey PRIMARY KEY (phase_id, environment_id);

ALTER TABLE ONLY phase
    ADD CONSTRAINT phase_pkey PRIMARY KEY (id);

ALTER TABLE ONLY scoped_user_role_environment
    ADD CONSTRAINT pk_scoped_user_role_environment PRIMARY KEY (scoped_user_role_id, environment_id);

ALTER TABLE ONLY scoped_user_role_project
    ADD CONSTRAINT pk_scoped_user_role_project PRIMARY KEY (scoped_user_role_id, project_id);

ALTER TABLE ONLY scoped_user_role_project_group
    ADD CONSTRAINT pk_scoped_user_role_project_group PRIMARY KEY (scoped_user_role_id, project_group_id);

ALTER TABLE ONLY team_member
    ADD CONSTRAINT pk_team_member PRIMARY KEY (team_id, user_id);

ALTER TABLE ONLY user_role_permission
    ADD CONSTRAINT pk_user_role_permission PRIMARY KEY (user_role_id, permission);

ALTER TABLE ONLY deployment_process_snapshot
    ADD CONSTRAINT process_snapshot_pkey PRIMARY KEY (id);

ALTER TABLE ONLY project_group
    ADD CONSTRAINT project_group_pkey PRIMARY KEY (id);

ALTER TABLE ONLY project
    ADD CONSTRAINT project_pkey PRIMARY KEY (id);

ALTER TABLE ONLY release
    ADD CONSTRAINT release_pkey PRIMARY KEY (id);

ALTER TABLE ONLY release_selected_package
    ADD CONSTRAINT release_selected_package_pkey PRIMARY KEY (id);

ALTER TABLE ONLY scoped_user_role
    ADD CONSTRAINT scoped_user_role_pkey PRIMARY KEY (id);

ALTER TABLE ONLY server_task_log
    ADD CONSTRAINT server_task_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY server_task
    ADD CONSTRAINT server_task_pkey PRIMARY KEY (id);

ALTER TABLE ONLY space
    ADD CONSTRAINT space_pkey PRIMARY KEY (id);

ALTER TABLE ONLY target_tag
    ADD CONSTRAINT target_tag_name_key UNIQUE (name);

ALTER TABLE ONLY target_tag
    ADD CONSTRAINT target_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY team
    ADD CONSTRAINT team_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_account_api_key
    ADD CONSTRAINT user_account_api_key_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_account
    ADD CONSTRAINT user_account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_role
    ADD CONSTRAINT user_role_pkey PRIMARY KEY (id);

ALTER TABLE ONLY variable
    ADD CONSTRAINT variable_pkey PRIMARY KEY (id);

ALTER TABLE ONLY variable_scope
    ADD CONSTRAINT variable_scope_pkey PRIMARY KEY (id);

ALTER TABLE ONLY variable_set
    ADD CONSTRAINT variable_set_pkey PRIMARY KEY (id);

ALTER TABLE ONLY variable_set_snapshot
    ADD CONSTRAINT variable_set_snapshot_pkey PRIMARY KEY (id);

CREATE INDEX ix_activity_log_parent_id ON activity_log USING btree (parent_id);

CREATE INDEX ix_activity_log_task_id ON activity_log USING btree (server_task_id);

CREATE INDEX ix_channel_version_rules_channel_id ON channel_version_rules USING btree (channel_id);

CREATE INDEX ix_deployment_action_property_action_id ON deployment_action_property USING btree (action_id);

CREATE INDEX ix_deployment_action_step_id ON deployment_action USING btree (step_id);

CREATE UNIQUE INDEX ix_deployment_action_step_order ON deployment_action USING btree (step_id, action_order);

CREATE UNIQUE INDEX ix_deployment_execution_checkpoint_server_task_id ON deployment_execution_checkpoint USING btree (server_task_id);

CREATE INDEX ix_deployment_interruption_server_task_id ON deployment_interruption USING btree (server_task_id);

CREATE INDEX ix_deployment_process_space_id ON deployment_process USING btree (space_id);

CREATE INDEX ix_deployment_step_process_id ON deployment_step USING btree (process_id);

CREATE UNIQUE INDEX ix_deployment_step_process_order ON deployment_step USING btree (process_id, step_order);

CREATE INDEX ix_deployment_step_property_step_id ON deployment_step_property USING btree (step_id);

CREATE INDEX ix_machine_endpoint_subscription_id ON machine USING btree ((((endpoint)::jsonb ->> 'SubscriptionId'::text))) WHERE (((endpoint)::jsonb ->> 'SubscriptionId'::text) IS NOT NULL);

CREATE INDEX ix_process_snapshot_content_hash ON deployment_process_snapshot USING btree (content_hash);

CREATE INDEX ix_process_snapshot_created ON deployment_process_snapshot USING btree (created_date DESC);

CREATE INDEX ix_process_snapshot_original_hash ON deployment_process_snapshot USING btree (original_process_id, content_hash);

CREATE UNIQUE INDEX ix_release_project_channel_version ON release USING btree (project_id, channel_id, version);

CREATE INDEX ix_scoped_user_role_space_id ON scoped_user_role USING btree (space_id);

CREATE INDEX ix_scoped_user_role_team_id ON scoped_user_role USING btree (team_id);

CREATE INDEX ix_server_task_concurrency_tag_state ON server_task USING btree (concurrency_tag, state) WHERE (concurrency_tag IS NOT NULL);

CREATE INDEX ix_server_task_log_task_id ON server_task_log USING btree (server_task_id);

CREATE INDEX ix_server_task_log_task_node_seq ON server_task_log USING btree (server_task_id, activity_node_id, sequence_number);

CREATE INDEX ix_server_task_log_task_seq ON server_task_log USING btree (server_task_id, sequence_number);

CREATE INDEX ix_snapshot_content_hash ON variable_set_snapshot USING btree (content_hash);

CREATE INDEX ix_snapshot_created ON variable_set_snapshot USING btree (created_date DESC);

CREATE INDEX ix_team_member_user_id ON team_member USING btree (user_id);

CREATE INDEX ix_user_account_api_key_user_account_id ON user_account_api_key USING btree (user_account_id);

CREATE UNIQUE INDEX ix_user_role_name ON user_role USING btree (name);

CREATE INDEX ix_variable_scope_type_value ON variable_scope USING btree (scope_type, scope_value);

CREATE INDEX ix_variable_scope_variable ON variable_scope USING btree (variable_id);

CREATE INDEX ix_variable_set_owner ON variable_set USING btree (owner_type, owner_id);

CREATE INDEX ix_variable_set_space ON variable_set USING btree (space_id);

CREATE INDEX ix_variable_sort_order ON variable USING btree (variable_set_id, sort_order, name);

CREATE INDEX ix_variable_variable_set_name ON variable USING btree (variable_set_id, name);

CREATE UNIQUE INDEX ux_user_account_api_key_api_key ON user_account_api_key USING btree (api_key);

CREATE UNIQUE INDEX ux_user_account_normalized_user_name ON user_account USING btree (normalized_user_name);

ALTER TABLE ONLY scoped_user_role_environment
    ADD CONSTRAINT scoped_user_role_environment_scoped_user_role_id_fkey FOREIGN KEY (scoped_user_role_id) REFERENCES scoped_user_role(id) ON DELETE CASCADE;

ALTER TABLE ONLY scoped_user_role_project_group
    ADD CONSTRAINT scoped_user_role_project_group_scoped_user_role_id_fkey FOREIGN KEY (scoped_user_role_id) REFERENCES scoped_user_role(id) ON DELETE CASCADE;

ALTER TABLE ONLY scoped_user_role_project
    ADD CONSTRAINT scoped_user_role_project_scoped_user_role_id_fkey FOREIGN KEY (scoped_user_role_id) REFERENCES scoped_user_role(id) ON DELETE CASCADE;

ALTER TABLE ONLY scoped_user_role
    ADD CONSTRAINT scoped_user_role_team_id_fkey FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE;

ALTER TABLE ONLY scoped_user_role
    ADD CONSTRAINT scoped_user_role_user_role_id_fkey FOREIGN KEY (user_role_id) REFERENCES user_role(id) ON DELETE CASCADE;

ALTER TABLE ONLY team_member
    ADD CONSTRAINT team_member_team_id_fkey FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE;

ALTER TABLE ONLY user_role_permission
    ADD CONSTRAINT user_role_permission_user_role_id_fkey FOREIGN KEY (user_role_id) REFERENCES user_role(id) ON DELETE CASCADE;

-- ============================================================
-- Seed Data
-- ============================================================

INSERT INTO user_account (
    id, user_name, normalized_user_name, display_name,
    password_hash, is_disabled, is_system, created_date, last_modified_date
)
SELECT
    8888, 'internal_user', 'INTERNAL_USER', 'internal_user',
    '', FALSE, TRUE, NOW(), NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM user_account
    WHERE id = 8888 OR normalized_user_name = 'INTERNAL_USER'
);
