-- Persisted audit Event stream — Squid's deployment/document "history" (parity
-- with Octopus Event documents). Append-only, lean (smallint enums, jsonb
-- structured refs, first-class indexed document columns), with snapshots kept in
-- a separate lazy side table so the hot feed table stays small.
--
-- Non-partitioned for now (partition-ready: `occurred` is the future RANGE key,
-- and is indexed for time-based retention). Range partitioning + a roll-forward
-- job is the immediate follow-up before deployment-lifecycle emission goes live.

CREATE TABLE IF NOT EXISTS event (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category         smallint NOT NULL,
    references_json  jsonb NOT NULL DEFAULT '{}'::jsonb,
    space_id         integer NOT NULL,
    project_id       integer,
    release_id       integer,
    deployment_id    integer,
    environment_id   integer,
    machine_id       integer,
    server_task_id   integer,
    user_id          integer,
    username         character varying(256) NOT NULL DEFAULT 'system',
    established_with smallint NOT NULL DEFAULT 0,
    user_agent       character varying(512),
    occurred         timestamp with time zone NOT NULL
);

-- Global space feed (newest first) and time-based retention prune.
CREATE INDEX IF NOT EXISTS ix_event_space_occurred ON event (space_id, occurred DESC);
CREATE INDEX IF NOT EXISTS ix_event_occurred ON event (occurred);

-- Per-document feeds: keyset paginated by id (monotonic == chronological).
-- Partial (WHERE ... IS NOT NULL) so each index only covers rows that relate to
-- that document type — smaller indexes, faster scans.
CREATE INDEX IF NOT EXISTS ix_event_release ON event (release_id, id) WHERE release_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_event_project ON event (project_id, id) WHERE project_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_event_environment ON event (environment_id, id) WHERE environment_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_event_machine ON event (machine_id, id) WHERE machine_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_event_deployment ON event (deployment_id, id) WHERE deployment_id IS NOT NULL;

-- Lazy snapshot side table (document Created/Modified/Deleted). jsonb is
-- TOAST-compressed; FK cascade so pruning an event prunes its snapshot.
CREATE TABLE IF NOT EXISTS event_document_snapshot (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    bigint NOT NULL REFERENCES event (id) ON DELETE CASCADE,
    before_json jsonb,
    after_json  jsonb
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_event_document_snapshot_event ON event_document_snapshot (event_id);
