CREATE TABLE IF NOT EXISTS octopus_import_session
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id uuid NOT NULL,
    destination_space_id integer NOT NULL,
    owner_user_id integer NOT NULL,
    state varchar(32) NOT NULL,
    source_summary_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    redacted_normalized_data_json jsonb NULL,
    validated_plan_json jsonb NULL,
    result_json jsonb NULL,
    data_version bytea NOT NULL,
    expires_at timestamptz NOT NULL,
    completed_at timestamptz NULL,
    last_state_changed_at timestamptz NOT NULL,
    created_date timestamptz NOT NULL DEFAULT now(),
    created_by integer NOT NULL DEFAULT 8888,
    last_modified_date timestamptz NOT NULL DEFAULT now(),
    last_modified_by integer NOT NULL DEFAULT 8888
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_octopus_import_session_session_id
    ON octopus_import_session (session_id);

CREATE INDEX IF NOT EXISTS ix_octopus_import_session_owner_space_session
    ON octopus_import_session (owner_user_id, destination_space_id, session_id);

CREATE INDEX IF NOT EXISTS ix_octopus_import_session_space_state
    ON octopus_import_session (destination_space_id, state);

CREATE INDEX IF NOT EXISTS ix_octopus_import_session_expires_at
    ON octopus_import_session (expires_at);
