tentacle:
  image:
    repository: squidcd/squid-tentacle
    tag: ""
    pullPolicy: IfNotPresent
  serverUrl: ""
  serverCommsUrl: ""
  bearerToken: ""
  serverCertificate: ""
  roles:
    - "k8s"
  machineName: ""
  environments: []
  spaceId: 1
  flavor: "KubernetesAgent"
  subscriptionId: ""

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  healthCheckPort: 8080

  startupProbe:
    failureThreshold: 100
    periodSeconds: 1

  terminationGracePeriodSeconds: 600

  tolerations: []
  affinity: {}
  metadata:
    annotations: {}
    labels: {}

kubernetes:
  namespace: "default"

scriptPod:
  image: bitnami/kubectl:latest
  serviceAccount: ""
  cpuRequest: "25m"
  memoryRequest: "100Mi"
  cpuLimit: "500m"
  memoryLimit: "512Mi"
  timeoutSeconds: 1800
  disruptionBudgetEnabled: true
  tolerations: []
  affinity: {}
  metadata:
    annotations: {}
    labels: {}

  rbac:
    useNamespacedRoles: false
    targetNamespaces: []
    clusterRole:
      rules:
      - apiGroups: ["*"]
        resources: ["*"]
        verbs: ["*"]
      - nonResourceURLs: ["*"]
        verbs: ["*"]

workspace:
  storageClassName: ""
  size: 10Gi
  accessModes:
    - ReadWriteMany
