tentacle:
  image:
    repository: squidcd/squid-tentacle
    tag: ""
    pullPolicy: IfNotPresent
  serverUrl: ""
  serverCommsUrl: ""
  serverCommsAddresses: []
  pollingConnectionCount: 5
  bearerToken: ""
  apiKey: ""
  serverCertificate: ""
  roles:
    - "k8s"
  machineName: ""
  chartRef: "oci://registry-1.docker.io/squidcd/kubernetes-agent"
  environments: []
  spaceId: 1
  flavor: "KubernetesAgent"
  subscriptionId: ""

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  healthCheckPort: 8080

  startupProbe:
    failureThreshold: 100
    periodSeconds: 1

  terminationGracePeriodSeconds: 600

  tolerations: []
  affinity: {}
  metadata:
    annotations: {}
    labels: {}

kubernetes:
  namespace: "default"

scriptPod:
  image: bitnami/kubectl:latest
  serviceAccount: ""
  isolateWorkspace: false
  cpuRequest: "25m"
  memoryRequest: "100Mi"
  cpuLimit: "500m"
  memoryLimit: "512Mi"
  timeoutSeconds: 1800
  disruptionBudgetEnabled: true
  tolerations: []
  affinity: {}
  metadata:
    annotations: {}
    labels: {}

  rbac:
    useNamespacedRoles: false
    targetNamespaces: []
    clusterRole:
      rules:
      - apiGroups: ["*"]
        resources: ["*"]
        verbs: ["*"]
      - nonResourceURLs: ["*"]
        verbs: ["*"]

workspace:
  storageClassName: ""
  volumeName: ""
  size: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ""
    path: "/squid-workspace"
    mountOptions:
      - nfsvers=4.1
      - soft
      - timeo=50
      - retrans=4
      - lookupcache=none
    image:
      repository: squidcd/nfs-server
      tag: ""
      pullPolicy: IfNotPresent
    backingVolume:
      storageClassName: ""
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

watchdog:
  enabled: true
  image:
    repository: squidcd/squid-watchdog
    tag: ""
    pullPolicy: IfNotPresent
  loopSeconds: ""
  initialBackoffSeconds: ""
  timeoutSeconds: ""
  resources:
    requests:
      memory: "32Mi"
      cpu: "10m"
    limits:
      memory: "64Mi"
      cpu: "50m"
