using System.Text;
using Squid.Core.Services.DeploymentExecution.Infrastructure;
using Squid.Core.Services.DeploymentExecution.Intents;
using Squid.Core.Services.DeploymentExecution.Script.Files;
using Squid.Message.Models.Deployments.Execution;

namespace Squid.Core.Services.DeploymentExecution.Kubernetes.Rendering;

/// <summary>
/// Builds the <c>helm upgrade --install</c> shell script from a <see cref="HelmUpgradeIntent"/>.
/// Produces both Bash and PowerShell variants. Extracted as a static utility so both
/// <see cref="KubernetesApiIntentRenderer"/> and <see cref="KubernetesAgentIntentRenderer"/>
/// share a single implementation.
/// </summary>
internal static class HelmUpgradeScriptBuilder
{
    /// <summary>
    /// P0-Phase10.2 (audit C.2): generated YAML file name for inline values.
    /// Lives in the per-task workspace (0700 perms via Phase-9.2 invariant)
    /// and is cleaned up by the existing finally-block. Pinned literal —
    /// scripts reference it; rename would silently break Helm's value chain.
    /// </summary>
    internal const string InlineValuesFileName = "inline-values.yaml";

    internal static string Build(HelmUpgradeIntent intent, ScriptSyntax syntax)
    {
        return syntax == ScriptSyntax.Bash
            ? BuildBash(intent)
            : BuildPowerShell(intent);
    }

    internal static DeploymentFileCollection BuildDeploymentFiles(HelmUpgradeIntent intent)
    {
        var files = new List<DeploymentFile>(intent.ValuesFiles);

        // P0-Phase10.2: project inline values to a YAML file rather than
        // emit them as `--set key=value` argv. Argv is visible to ps,
        // /proc/<pid>/cmdline, kubelet logs, audit logs, bash trace —
        // unacceptable for sensitive values (DB password, API key, TLS
        // private key). The generated file lives in the workspace and is
        // cleaned up after deploy.
        var inlineFile = TryGenerateInlineValuesFile(intent.InlineValues);
        if (inlineFile != null)
            files.Add(inlineFile);

        if (files.Count == 0) return DeploymentFileCollection.Empty;

        return new DeploymentFileCollection(files);
    }

    /// <summary>
    /// Returns a generated DeploymentFile carrying <paramref name="inlineValues"/>
    /// as nested YAML, or null if the dictionary is empty (no need to
    /// generate an empty file). Dotted keys like <c>database.password</c>
    /// produce nested YAML structure (preserves Helm's standard
    /// <c>--set</c> dot-notation semantics).
    ///
    /// <c>internal</c> for direct unit testing.
    /// </summary>
    internal static DeploymentFile TryGenerateInlineValuesFile(IReadOnlyDictionary<string, string> inlineValues)
    {
        if (inlineValues == null || inlineValues.Count == 0) return null;

        var yaml = RenderInlineValuesAsYaml(inlineValues);
        var bytes = System.Text.Encoding.UTF8.GetBytes(yaml);
        return DeploymentFile.Asset(InlineValuesFileName, bytes);
    }

    /// <summary>
    /// Renders dotted-key inline values as nested YAML. Builds a tree of
    /// nested dictionaries from dotted paths so <c>database.host</c> +
    /// <c>database.password</c> produce a single <c>database:</c> block —
    /// matching Helm's <c>--set</c> dot-notation semantics. String values
    /// are emitted in single-quoted YAML form (preserves any embedded
    /// special chars like <c>'</c> via doubling).
    /// </summary>
    private static string RenderInlineValuesAsYaml(IReadOnlyDictionary<string, string> inlineValues)
    {
        // Build a tree: Dictionary<string, object> where leaf values are
        // strings and intermediate nodes are nested Dictionary<string,object>.
        var tree = new SortedDictionary<string, object>(StringComparer.Ordinal);

        foreach (var kvp in inlineValues)
        {
            var path = kvp.Key.Split('.');
            InsertIntoTree(tree, path, 0, kvp.Value);
        }

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Squid HelmUpgradeScriptBuilder (P0-Phase10.2)");
        sb.AppendLine("# Inline values projected from action.InlineValues so secrets do");
        sb.AppendLine("# NOT land in helm argv (visible to ps / kubelet logs / audit).");
        EmitYamlTree(sb, tree, indent: 0);
        return sb.ToString();
    }

    private static void InsertIntoTree(SortedDictionary<string, object> node, string[] path, int depth, string leafValue)
    {
        var key = path[depth];
        if (depth == path.Length - 1)
        {
            node[key] = leafValue;
            return;
        }

        if (!node.TryGetValue(key, out var existing) || existing is not SortedDictionary<string, object> child)
        {
            child = new SortedDictionary<string, object>(StringComparer.Ordinal);
            node[key] = child;
        }

        InsertIntoTree(child, path, depth + 1, leafValue);
    }

    private static void EmitYamlTree(StringBuilder sb, SortedDictionary<string, object> tree, int indent)
    {
        var pad = new string(' ', indent * 2);

        foreach (var kvp in tree)
        {
            switch (kvp.Value)
            {
                case SortedDictionary<string, object> nested:
                    sb.AppendLine($"{pad}{kvp.Key}:");
                    EmitYamlTree(sb, nested, indent + 1);
                    break;
                case string s:
                    // YAML single-quoted form: escape internal ' by doubling it
                    var escaped = s.Replace("'", "''", StringComparison.Ordinal);
                    sb.AppendLine($"{pad}{kvp.Key}: '{escaped}'");
                    break;
            }
        }
    }

    private static string BuildBash(HelmUpgradeIntent intent)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/usr/bin/env bash");
        sb.AppendLine("set -euo pipefail");

        AppendBashRepoSetup(sb, intent.Repository);
        AppendBashHelmCommand(sb, intent);

        return sb.ToString();
    }

    private static void AppendBashRepoSetup(StringBuilder sb, HelmRepository? repo)
    {
        if (repo == null) return;

        var url = ShellEscapeHelper.EscapeBash(repo.Url);
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(repo.Username) && !string.IsNullOrWhiteSpace(repo.Password))
        {
            var user = ShellEscapeHelper.EscapeBash(repo.Username!);
            var pass = ShellEscapeHelper.EscapeBash(repo.Password!);
            sb.AppendLine($"helm repo add \"{repo.Name}\" \"{url}\" --username \"{user}\" --password \"{pass}\" --force-update");
        }
        else
        {
            sb.AppendLine($"helm repo add \"{repo.Name}\" \"{url}\" --force-update");
        }

        sb.AppendLine($"helm repo update \"{repo.Name}\"");
    }

    private static void AppendBashHelmCommand(StringBuilder sb, HelmUpgradeIntent intent)
    {
        var helmExe = string.IsNullOrEmpty(intent.CustomHelmExecutable) ? "helm" : intent.CustomHelmExecutable;

        sb.AppendLine();
        sb.Append($"\"{helmExe}\" upgrade --install \"{intent.ReleaseName}\" \"{intent.ChartReference}\"");

        if (!string.IsNullOrEmpty(intent.Namespace))
            sb.Append($" --namespace \"{intent.Namespace}\"");

        if (intent.ResetValues)
            sb.Append(" --reset-values");

        if (intent.Wait)
            sb.Append(" --wait");

        if (intent.WaitForJobs)
            sb.Append(" --wait-for-jobs");

        if (!string.IsNullOrEmpty(intent.Timeout))
            sb.Append($" --timeout \"{intent.Timeout}\"");

        if (!string.IsNullOrEmpty(intent.ChartVersion))
            sb.Append($" --version \"{intent.ChartVersion}\"");

        AppendBashValuesFiles(sb, intent);
        AppendBashInlineValuesAsFile(sb, intent);

        if (!string.IsNullOrEmpty(intent.AdditionalArgs))
            sb.Append($" {intent.AdditionalArgs}");

        sb.AppendLine();
    }

    private static void AppendBashValuesFiles(StringBuilder sb, HelmUpgradeIntent intent)
    {
        foreach (var file in intent.ValuesFiles)
            sb.Append($" --values \"./{file.RelativePath}\"");
    }

    /// <summary>
    /// P0-Phase10.2: emit a SECOND <c>--values</c> for the generated
    /// inline-values.yaml file (only when there ARE inline values). Comes
    /// AFTER the user-supplied values files so it overrides them — matches
    /// pre-fix <c>--set</c> precedence semantics.
    /// </summary>
    private static void AppendBashInlineValuesAsFile(StringBuilder sb, HelmUpgradeIntent intent)
    {
        if (intent.InlineValues == null || intent.InlineValues.Count == 0) return;

        sb.Append($" --values \"./{InlineValuesFileName}\"");
    }

    private static string BuildPowerShell(HelmUpgradeIntent intent)
    {
        var sb = new StringBuilder();
        sb.AppendLine("$ErrorActionPreference = \"Stop\"");

        AppendPowerShellRepoSetup(sb, intent.Repository);
        AppendPowerShellHelmCommand(sb, intent);

        return sb.ToString();
    }

    private static void AppendPowerShellRepoSetup(StringBuilder sb, HelmRepository? repo)
    {
        if (repo == null) return;

        var url = ShellEscapeHelper.EscapePowerShell(repo.Url);
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(repo.Username) && !string.IsNullOrWhiteSpace(repo.Password))
        {
            var user = ShellEscapeHelper.EscapePowerShell(repo.Username!);
            var pass = ShellEscapeHelper.EscapePowerShell(repo.Password!);
            sb.AppendLine($"& helm repo add \"{repo.Name}\" \"{url}\" --username \"{user}\" --password \"{pass}\" --force-update 2>$null");
        }
        else
        {
            sb.AppendLine($"& helm repo add \"{repo.Name}\" \"{url}\" --force-update 2>$null");
        }

        sb.AppendLine($"& helm repo update \"{repo.Name}\" 2>$null");
    }

    private static void AppendPowerShellHelmCommand(StringBuilder sb, HelmUpgradeIntent intent)
    {
        var helmExe = string.IsNullOrEmpty(intent.CustomHelmExecutable) ? "helm" : intent.CustomHelmExecutable;

        sb.AppendLine();
        sb.AppendLine($"$helmArgs = @(\"upgrade\", \"--install\", \"{intent.ReleaseName}\", \"{intent.ChartReference}\")");

        if (!string.IsNullOrEmpty(intent.Namespace))
            sb.AppendLine($"$helmArgs += \"--namespace\"; $helmArgs += \"{intent.Namespace}\"");

        if (intent.ResetValues)
            sb.AppendLine("$helmArgs += \"--reset-values\"");

        if (intent.Wait)
            sb.AppendLine("$helmArgs += \"--wait\"");

        if (intent.WaitForJobs)
            sb.AppendLine("$helmArgs += \"--wait-for-jobs\"");

        if (!string.IsNullOrEmpty(intent.Timeout))
            sb.AppendLine($"$helmArgs += \"--timeout\"; $helmArgs += \"{intent.Timeout}\"");

        if (!string.IsNullOrEmpty(intent.ChartVersion))
            sb.AppendLine($"$helmArgs += \"--version\"; $helmArgs += \"{intent.ChartVersion}\"");

        AppendPowerShellValuesFiles(sb, intent);
        AppendPowerShellInlineValuesAsFile(sb, intent);

        if (!string.IsNullOrEmpty(intent.AdditionalArgs))
        {
            var escaped = ShellEscapeHelper.EscapePowerShell(intent.AdditionalArgs);
            sb.AppendLine($"$helmArgs += (\"{escaped}\" -split '\\s+(?=--?)') | ForEach-Object {{ $_.Trim() }} | Where-Object {{ $_ -ne '' }}");
        }

        sb.AppendLine($"& \"{helmExe}\" @helmArgs");
        sb.AppendLine("if ($LASTEXITCODE -ne 0) { throw \"Helm upgrade failed with exit code $LASTEXITCODE\" }");
    }

    private static void AppendPowerShellValuesFiles(StringBuilder sb, HelmUpgradeIntent intent)
    {
        foreach (var file in intent.ValuesFiles)
            sb.AppendLine($"$helmArgs += \"--values\"; $helmArgs += \".\\{file.RelativePath.Replace("/", "\\", StringComparison.Ordinal)}\"");
    }

    /// <summary>
    /// P0-Phase10.2: PowerShell mirror of <see cref="AppendBashInlineValuesAsFile"/>.
    /// Same generated inline-values.yaml file referenced via <c>--values</c>.
    /// Path uses Windows-style backslashes when running on PowerShell.
    /// </summary>
    private static void AppendPowerShellInlineValuesAsFile(StringBuilder sb, HelmUpgradeIntent intent)
    {
        if (intent.InlineValues == null || intent.InlineValues.Count == 0) return;

        sb.AppendLine($"$helmArgs += \"--values\"; $helmArgs += \".\\{InlineValuesFileName}\"");
    }
}
