apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "squid-agent.fullname" . }}-config
  labels:
    {{- include "squid-agent.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "Agent": {
        "ServerUrl": "{{ .Values.agent.serverUrl }}",
        "ServerPollingPort": {{ .Values.agent.serverPollingPort }},
        "Namespace": "{{ .Values.agent.namespace }}",
        "Roles": "{{ .Values.agent.roles }}",
        "UseScriptPods": true,
        "ScriptPodImage": "{{ .Values.scriptPod.image }}",
        "ScriptPodTimeoutSeconds": {{ .Values.scriptPod.timeoutSeconds }}
      }
    }
