{{- if .Values.scriptPod.rbac.useNamespacedRoles }}
{{- $namespaces := .Values.scriptPod.rbac.targetNamespaces }}
{{- if not $namespaces }}
{{- $namespaces = list .Release.Namespace }}
{{- end }}
{{- range $ns := $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "squid-agent.fullname" $ }}-script
  namespace: {{ $ns }}
  labels:
    {{- include "squid-agent.labels" $ | nindent 4 }}
rules:
  {{- toYaml $.Values.scriptPod.rbac.clusterRole.rules | nindent 2 }}
{{- end }}
{{- end }}
