apiVersion: v1
kind: Secret
metadata:
  name: {{ include "squid-agent.fullname" . }}-secret
  labels:
    {{- include "squid-agent.labels" . | nindent 4 }}
type: Opaque
data:
  bearer-token: {{ .Values.agent.bearerToken | b64enc | quote }}
