#!/usr/bin/env bash
# ============================================================================
# Squid Tentacle — End-to-end upgrade validation script
# ----------------------------------------------------------------------------
# Spins up a systemd-enabled Docker container for a given Linux distribution,
# installs a specified starting version of the tentacle, registers it to a
# running Squid server, and waits for the operator to trigger UI Upgrade.
# Then verifies the status-file schema + final version + clean log output.
#
# Primary motivation (D1, 1.5.0): the yum/dnf upgrade path was designed,
# unit-tested, and audited — but NEVER exercised E2E against a real RPM-based
# host. This script closes that gap. Secondary: gives us a reproducible test
# rig for future distros (Fedora, Alma, Debian, Alpine — see D3 matrix).
#
# Usage:
#     ./deploy/scripts/e2e-upgrade-test.sh rocky-9            1.4.4 1.5.0
#     ./deploy/scripts/e2e-upgrade-test.sh ubuntu-22.04       1.4.4 1.5.0
#     ./deploy/scripts/e2e-upgrade-test.sh debian-12          1.4.4 1.5.0
#     ./deploy/scripts/e2e-upgrade-test.sh fedora-40          1.4.4 1.5.0
#
# Env vars (either provide on command line or export):
#     SQUID_SERVER_URL          https://squid-api-test.solarifyai.com
#     SQUID_POLLING_URL         https://squid-polling-test.solarifyai.com:10943
#     SQUID_API_KEY             API-xxxxxxxxxxxx
#     SQUID_SERVER_THUMBPRINT   FAF04764A5...
#     SQUID_SPACE_ID            1 (default)
#     SQUID_TEST_ROLE           e2e-test-agent (default)
#     SQUID_TEST_ENVIRONMENT    TEST (default)
# ============================================================================
set -euo pipefail

DISTRO="${1:-}"
START_VERSION="${2:-}"
TARGET_VERSION="${3:-}"

if [ -z "$DISTRO" ] || [ -z "$START_VERSION" ] || [ -z "$TARGET_VERSION" ]; then
  echo "Usage: $0 <distro> <start-version> <target-version>"
  echo "       distros: rocky-9 | ubuntu-22.04 | debian-12 | fedora-40 | almalinux-9"
  exit 1
fi

: "${SQUID_SERVER_URL:?SQUID_SERVER_URL required}"
: "${SQUID_POLLING_URL:?SQUID_POLLING_URL required}"
: "${SQUID_API_KEY:?SQUID_API_KEY required}"
: "${SQUID_SERVER_THUMBPRINT:?SQUID_SERVER_THUMBPRINT required}"
SQUID_SPACE_ID="${SQUID_SPACE_ID:-1}"
SQUID_TEST_ROLE="${SQUID_TEST_ROLE:-e2e-test-agent}"
SQUID_TEST_ENVIRONMENT="${SQUID_TEST_ENVIRONMENT:-TEST}"

# ── Distro → Docker image + package-manager binary map ────────────────────────
# jrei/systemd-* images are the standard systemd-in-docker option for RPM/Deb
# families; Alpine uses a different path (D2) not covered here.
case "$DISTRO" in
  rocky-9)      IMAGE=jrei/systemd-rockylinux:9         ; PKG_MANAGER=dnf ;;
  almalinux-9)  IMAGE=jrei/systemd-almalinux:9          ; PKG_MANAGER=dnf ;;
  fedora-40)    IMAGE=jrei/systemd-fedora:40            ; PKG_MANAGER=dnf ;;
  ubuntu-20.04) IMAGE=jrei/systemd-ubuntu:20.04         ; PKG_MANAGER=apt ;;
  ubuntu-22.04) IMAGE=jrei/systemd-ubuntu:22.04         ; PKG_MANAGER=apt ;;
  ubuntu-24.04) IMAGE=jrei/systemd-ubuntu:24.04         ; PKG_MANAGER=apt ;;
  debian-12)    IMAGE=jrei/systemd-debian:12            ; PKG_MANAGER=apt ;;
  *) echo "::error:: Unsupported distro: $DISTRO"; exit 1 ;;
esac

CONTAINER_NAME="squid-e2e-${DISTRO}"
MACHINE_NAME="e2e-${DISTRO}-$(date +%s)"

echo "=== Squid Tentacle E2E Upgrade Test ==="
echo "Distro:           $DISTRO ($IMAGE)"
echo "Package manager:  $PKG_MANAGER"
echo "Start version:    $START_VERSION"
echo "Target version:   $TARGET_VERSION"
echo "Machine name:     $MACHINE_NAME"
echo "Container name:   $CONTAINER_NAME"
echo ""

# ── Step 1 — Launch systemd container ────────────────────────────────────────
echo "[1/6] Launching systemd container..."
docker rm -f "$CONTAINER_NAME" 2>/dev/null || true
docker run -d \
  --name "$CONTAINER_NAME" \
  --hostname "$MACHINE_NAME" \
  --privileged \
  --cgroupns=host \
  -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
  --tmpfs /run \
  --tmpfs /run/lock \
  "$IMAGE" >/dev/null

sleep 5  # systemd boot

# Verify systemd is up
if ! docker exec "$CONTAINER_NAME" systemctl is-system-running --wait 2>/dev/null | grep -qE "running|degraded"; then
  echo "::error:: systemd didn't come up in $CONTAINER_NAME"
  docker logs "$CONTAINER_NAME" | tail -20
  exit 1
fi

echo "  ✓ systemd running, version: $(docker exec "$CONTAINER_NAME" systemctl --version | head -1)"

# ── Step 2 — Install prerequisites (curl + sudo + gnupg) ─────────────────────
# Minimal images lack even `curl`. Install-tentacle.sh needs curl; register
# needs sudo (the register command itself may not, but the upgrade script
# generated by the server will).
echo ""
echo "[2/6] Installing prerequisites (curl + sudo)..."
if [ "$PKG_MANAGER" = "apt" ]; then
  docker exec "$CONTAINER_NAME" bash -c 'export DEBIAN_FRONTEND=noninteractive && apt-get update -qq && apt-get install -y -qq curl sudo gnupg ca-certificates' 2>&1 | tail -3
else
  docker exec "$CONTAINER_NAME" bash -c 'dnf install -y -q curl sudo gnupg2 ca-certificates' 2>&1 | tail -3
fi

# ── Step 3 — Run install-tentacle.sh (installs LATEST from the repo) ─────────
# Note: install-tentacle.sh without --version installs "latest" which after
# our release workflows = whatever is on Squid APT/RPM repo. For this E2E
# we'd ideally pin to START_VERSION, but reprepro (APT repo) keeps only
# the latest, so pin-ability is limited to GitHub Releases direct .deb/.rpm
# download. We accept that install-tentacle.sh may install latest here and
# rely on a follow-up downgrade to START_VERSION if needed.
echo ""
echo "[3/6] Running install-tentacle.sh..."
docker cp "$(dirname "$0")/install-tentacle.sh" "$CONTAINER_NAME":/tmp/install-tentacle.sh
docker exec "$CONTAINER_NAME" bash /tmp/install-tentacle.sh 2>&1 | tail -5

# Verify tentacle binary is installed
CURRENT_VERSION=$(docker exec "$CONTAINER_NAME" squid-tentacle version 2>/dev/null | head -1 || echo "not-installed")
echo "  ✓ tentacle installed, version: $CURRENT_VERSION"

# ── Step 3.5 — Downgrade to START_VERSION if needed ──────────────────────────
if [ "$CURRENT_VERSION" != "$START_VERSION" ]; then
  echo ""
  echo "[3.5/6] Downgrading from $CURRENT_VERSION to $START_VERSION for test setup..."
  if [ "$PKG_MANAGER" = "apt" ]; then
    ARCH=$(docker exec "$CONTAINER_NAME" dpkg --print-architecture)
    DEB_URL="https://github.com/SolarifyDev/Squid/releases/download/${START_VERSION}/squid-tentacle_${START_VERSION}_${ARCH}.deb"
    docker exec "$CONTAINER_NAME" bash -c "curl -fsSL -o /tmp/sq.deb '$DEB_URL' && dpkg -i --force-downgrade /tmp/sq.deb" 2>&1 | tail -3 || true
  else
    # dnf downgrade or explicit version install
    ARCH=$(docker exec "$CONTAINER_NAME" uname -m)
    [ "$ARCH" = "x86_64" ] && ARCH_RPM=x86_64 || ARCH_RPM=aarch64
    RPM_URL="https://github.com/SolarifyDev/Squid/releases/download/${START_VERSION}/squid-tentacle-${START_VERSION}-1.${ARCH_RPM}.rpm"
    docker exec "$CONTAINER_NAME" bash -c "curl -fsSL -o /tmp/sq.rpm '$RPM_URL' && rpm -U --oldpackage /tmp/sq.rpm" 2>&1 | tail -3 || true
  fi
  CURRENT_VERSION=$(docker exec "$CONTAINER_NAME" squid-tentacle version 2>/dev/null | head -1)
  echo "  ✓ now at: $CURRENT_VERSION"
fi

if [ "$CURRENT_VERSION" != "$START_VERSION" ]; then
  echo "::error:: failed to set up start version — got '$CURRENT_VERSION', wanted '$START_VERSION'"
  exit 1
fi

# ── Step 4 — Register + start service ────────────────────────────────────────
echo ""
echo "[4/6] Registering tentacle to server..."
docker exec \
  -e Tentacle__Flavor=LinuxTentacle \
  -e Tentacle__SpaceId="$SQUID_SPACE_ID" \
  -e Tentacle__ServerCertificate="$SQUID_SERVER_THUMBPRINT" \
  -e Tentacle__MachineName="$MACHINE_NAME" \
  "$CONTAINER_NAME" squid-tentacle register \
    --server "$SQUID_SERVER_URL" \
    --api-key "$SQUID_API_KEY" \
    --role "$SQUID_TEST_ROLE" \
    --environment "$SQUID_TEST_ENVIRONMENT" \
    --comms-url "$SQUID_POLLING_URL" 2>&1 | tail -5

docker exec "$CONTAINER_NAME" squid-tentacle service install 2>&1 | tail -2
docker exec "$CONTAINER_NAME" systemctl daemon-reload
docker exec "$CONTAINER_NAME" systemctl start squid-tentacle
sleep 3

# Verify polling connections
POLLING_COUNT=$(docker exec "$CONTAINER_NAME" journalctl -u squid-tentacle --no-pager 2>&1 | grep -c "Secure connection established" || echo 0)
echo "  ✓ polling connections established: $POLLING_COUNT"

# ── Step 5 — Wait for operator to click Upgrade in UI ────────────────────────
echo ""
echo "[5/6] === GO TO UI AND CLICK UPGRADE ==="
echo ""
echo "  Machine name:   $MACHINE_NAME"
echo "  Role:           $SQUID_TEST_ROLE"
echo "  Environment:    $SQUID_TEST_ENVIRONMENT"
echo "  Expected:       $CURRENT_VERSION → $TARGET_VERSION"
echo ""
echo "  Waiting up to 10 minutes for upgrade to complete..."
echo ""

DEADLINE=$(( $(date +%s) + 600 ))
LAST_STATUS=""
while [ "$(date +%s)" -lt "$DEADLINE" ]; do
  VERSION_NOW=$(docker exec "$CONTAINER_NAME" squid-tentacle version 2>/dev/null | head -1 || echo OFFLINE)
  STATUS_NOW=$(docker exec "$CONTAINER_NAME" sh -c 'grep -oE "\"status\": *\"[^\"]*\"" /var/lib/squid-tentacle/last-upgrade.json 2>/dev/null | head -1' || echo none)

  if [ "$STATUS_NOW" != "$LAST_STATUS" ] || [ "$VERSION_NOW" != "$START_VERSION" ]; then
    echo "    [$(date -u +%H:%M:%S)] version=$VERSION_NOW status=$STATUS_NOW"
    LAST_STATUS="$STATUS_NOW"
  fi

  if echo "$STATUS_NOW" | grep -q "SUCCESS"; then
    break
  fi
  case "$STATUS_NOW" in
    *FAILED*|*ROLLBACK*) break ;;
  esac

  sleep 5
done

# ── Step 6 — Assert final state ──────────────────────────────────────────────
echo ""
echo "[6/6] Asserting final state..."

FINAL_VERSION=$(docker exec "$CONTAINER_NAME" squid-tentacle version 2>/dev/null | head -1)
FINAL_STATUS=$(docker exec "$CONTAINER_NAME" cat /var/lib/squid-tentacle/last-upgrade.json 2>/dev/null || echo "{}")

echo ""
echo "Final version: $FINAL_VERSION"
echo "Final status file:"
echo "$FINAL_STATUS" | sed 's/^/  /'
echo ""

FAIL_COUNT=0
assert_contains() {
  local label="$1" haystack="$2" needle="$3"
  if echo "$haystack" | grep -q "$needle"; then
    echo "  ✓ $label"
  else
    echo "  ✗ $label — expected: $needle"
    FAIL_COUNT=$((FAIL_COUNT + 1))
  fi
}

assert_contains "final version matches target"    "$FINAL_VERSION"  "^$TARGET_VERSION\$"
assert_contains "status is SUCCESS"               "$FINAL_STATUS"   '"status":.*"SUCCESS"'
assert_contains "installMethod is $PKG_MANAGER"   "$FINAL_STATUS"   "\"installMethod\":.*\"$PKG_MANAGER\""
assert_contains "schemaVersion is 2+"             "$FINAL_STATUS"   '"schemaVersion":.*2'
assert_contains "startedAt present (A2 gating)"   "$FINAL_STATUS"   '"startedAt":'

# ── Cleanup (skip if SQUID_KEEP_CONTAINER set for post-mortem) ───────────────
echo ""
if [ -n "${SQUID_KEEP_CONTAINER:-}" ]; then
  echo "SQUID_KEEP_CONTAINER set — container '$CONTAINER_NAME' kept for inspection."
  echo "  docker exec -it $CONTAINER_NAME bash"
  echo "  docker rm -f $CONTAINER_NAME  # when done"
else
  docker rm -f "$CONTAINER_NAME" >/dev/null
  echo "Cleaned up container $CONTAINER_NAME."
fi

if [ "$FAIL_COUNT" -eq 0 ]; then
  echo ""
  echo "✓✓✓ E2E test PASSED for $DISTRO — $START_VERSION → $TARGET_VERSION via $PKG_MANAGER"
  exit 0
else
  echo ""
  echo "✗✗✗ E2E test FAILED for $DISTRO — $FAIL_COUNT assertion(s) failed"
  exit 1
fi
