apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubernetes-agent.pvc-name" . }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.workspace.accessModes | nindent 4 }}
  {{- if include "kubernetes-agent.useBuiltinNfs" . }}
  volumeName: {{ include "kubernetes-agent.nfs.pv-name" . }}
  storageClassName: ""
  {{- else if include "kubernetes-agent.useExternalNfs" . }}
  volumeName: {{ include "kubernetes-agent.fullname" . }}-pv
  storageClassName: ""
  {{- else }}
  {{- if .Values.workspace.volumeName }}
  volumeName: {{ .Values.workspace.volumeName }}
  {{- end }}
  {{- if .Values.workspace.storageClassName }}
  storageClassName: {{ .Values.workspace.storageClassName }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.workspace.size }}
