apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}-secret
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
type: Opaque
data:
  bearer-token: {{ .Values.tentacle.bearerToken | b64enc | quote }}
{{- if .Values.tentacle.apiKey }}
  api-key: {{ .Values.tentacle.apiKey | b64enc | quote }}
{{- end }}
