{{- if .Values.tentacle.serverCertificate }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes-agent.fullname" . }}-server-cert
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
data:
  server-cert.pem: {{ .Values.tentacle.serverCertificate }}
{{- end }}
