apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "squid-tentacle.fullname" . }}-config
  labels:
    {{- include "squid-tentacle.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "Tentacle": {
        "ServerUrl": "{{ .Values.tentacle.serverUrl }}",
        "ServerPollingPort": {{ .Values.tentacle.serverPollingPort }},
        "Roles": "{{ .Values.tentacle.roles }}"
      },
      "Kubernetes": {
        "Namespace": "{{ .Values.kubernetes.namespace }}",
        "UseScriptPods": true,
        "ScriptPodImage": "{{ .Values.scriptPod.image }}",
        "ScriptPodTimeoutSeconds": {{ .Values.scriptPod.timeoutSeconds }}
      }
    }
