apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "squid-tentacle.pvc-name" . }}
  labels:
    {{- include "squid-tentacle.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.workspace.accessModes | nindent 4 }}
  {{- if .Values.workspace.storageClassName }}
  storageClassName: {{ .Values.workspace.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.workspace.size }}
