apiVersion: v1
kind: Secret
metadata:
  name: {{ include "squid-tentacle.fullname" . }}-secret
  labels:
    {{- include "squid-tentacle.labels" . | nindent 4 }}
type: Opaque
data:
  bearer-token: {{ .Values.tentacle.bearerToken | b64enc | quote }}
